version: '3'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

